<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GitHubActionsTestLogger" Version="3.0.5" />
    <PackageReference Include="MartinCostello.BrowserStack.Automate" Version="4.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.Playwright" Version="1.62.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageReference Include="xunit.v3.mtp-off" Version="4.0.1" />
  </ItemGroup>
</Project>
